# Generated by Django 4.0.3 on 2023-01-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('token', models.TextField()),
                ('user_type', models.CharField(choices=[('u', 'u'), ('s', 's')], default='u', max_length=1)),
            ],
        ),
    ]
